---
# This playbook contains common plays that will be run on all nodes.

- name: Configure ntp file
  template: src=ntpd.conf.j2 dest=/etc/ntp/ntp.conf
  notify: restart ntp
  tags:
  - replicate

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags:
  - replicate

- name: install ceph-deploy
  yum: name=ceph-deploy state=latest
  tags:
  - replicate

- name: mkdir of ceph cluster
  file: path={{cluster_dir}} state=directory mode=0755
  tags:
  - replicate

- name: create new cluster
  shell: ceph-deploy new {{mon_node}} chdir={{cluster_dir}}
  tags:
  - replicate

- name: config ceph.conf
  template: src=ceph.conf.j2 dest={{cluster_dir}}/ceph.conf
  tags:
  - replicate

- name: create mon 
  command: ceph-deploy --overwrite-conf mon create-initial chdir={{cluster_dir}}
  tags:
  - replicate

- name: push ceph.client.admin.keyring to every node
  command: ceph-deploy admin {{cluster_node}} chdir={{cluster_dir}}
  tags:
  - replicate

- name: push ceph.conf to  every node
  command: ceph-deploy --overwrite-conf config push {{cluster_node}} chdir={{cluster_dir}}
  tags:
  - replicate

- name: compile crushmap
  command: crushtool -c crush_map.txt -o crush_map
  tags: 
  - replicate

- name: inject crushmap
  command: ceph osd setcrushmap -i crush_map
  tags:
  - replicate

- name: erasure_code 
  script: ./roles/admin/scripts/erasure_code.sh {{erasure_k}} {{erasure_m}}
  tags:
  - erasure_code

- name: uninstall ceph
  shell: ceph-deploy uninstall {{cluster_node}} 
  tags:
  - uninstall


- name: purge ceph
  shell: ceph-deploy purge {{cluster_node}} 
  tags:
  - uninstall


- name: purgedata ceph
  shell: ceph-deploy purgedata {{cluster_node}} 
  tags:
  - uninstall

- name: forgetkeys ceph
  shell: ceph-deploy forgetkeys
  tags:
  - uninstall

- name: remove ceph-deploy ceph
  yum: name=ceph-deploy state=absent
  tags:
  - uninstall

- name: remove cluster_dir
  file: path={{cluster_dir}} state=absent
  tags:
  - uninstall
