---
# This playbook contains common plays that will be run on all nodes.

- name: add osd
  script: ./roles/osd/scripts/add_osd.sh  {{ansible_nodename}} {{item}} 20 
  with_ini: disk* section={{ansible_nodename}} file=disk.ini re=true

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp/ntp.conf
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
